name: bloodleycooper
description: 
  Bloodley Co-Oper is an app for recording your blood pressure

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  english_words: ^3.1.0
  intl: "^0.15.2"
  path_provider: "^0.4.0"
  sqflite: any
  meta: "^1.1.2"
  square_calendar: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/bloodley.db
