name: bloodleycooper
version: 0.0.1
description: 
  Bloodley Co-Oper is an app for recording your blood pressure

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  intl: ^0.16.1
  path_provider: ^1.6.22
  sqflite: ^1.3.2+1
  meta: ^1.2.3
  square_calendar: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/bloodley.db
